Extract xtract
MLMI2-CSSI/foundry pull request #241
Opened 2022-08-06 16:45 UTC by blaiszik

2022-08-09 16:18 UTC, WardLT requested changes
Just documentation and code style complaints. 

We're also missing tests to make sure that this functions correctly. Can you do something where we xfer to a globus test endpoint?

2022-08-09 16:18 UTC, WardLT commented on foundry/foundry.py
> +def recursive_ls(tc, ep, path, max_depth=3):
Add some docstrings to these

2022-08-09 16:18 UTC, WardLT commented on foundry/foundry.py
> +def download_file(item, https_config):
Could you add a docstring and/or type hints? E.g., what content does "item" have and where does it usually come from? 

Additionally, the indentation is odd here. Does your editor have an autopep you could run on this?

2022-08-15 19:15 UTC, closed without merging

2022-08-15 19:27 UTC, ascourtas commented
closed since Ben already merged this into `main`